# Generated by Django 4.1.2 on 2022-10-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "number",
                    models.DecimalField(decimal_places=0, default=1, max_digits=999),
                ),
                ("level", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
