# Generated by Django 4.1.2 on 2022-10-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="symptoms",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="time",
            field=models.TimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="ward",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
