# Generated by Django 4.1.2 on 2022-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_patient_symptoms_patient_time_patient_ward"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="slug",
            field=models.SlugField(default="patient"),
        ),
    ]
