# Generated by Django 4.1.2 on 2022-10-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_alter_patient_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="slug",
        ),
    ]
