# Generated by Django 4.1.2 on 2022-11-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_remove_patient_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="Admitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="None_Admitted",
            field=models.BooleanField(default=False),
        ),
    ]
