# Generated by Django 4.1.2 on 2022-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="patient",
            field=models.BooleanField(default=False),
        ),
    ]
