# Generated by Django 4.1.2 on 2022-10-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ward",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
